'use strict';
/* Regression checks for shared core rules and real production DOM/input handlers. */
(async () => {
  const $ = id => document.getElementById(id);
  const Core = window.KuchiieCore;
  const snapshot = () => window.KuchiieDiagnostics.snapshot();
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const until = async (fn, name, timeout = 20000) => {
    const start = performance.now();
    while (!fn()) { if (performance.now() - start > timeout) throw new Error('Timeout: ' + name); await wait(50); }
  };
  let checks = 0;
  const assert = (value, name) => { if (!value) throw new Error(name); checks++; console.info('[AUDIT PASS] ' + name); };
  const key = (type, code, repeat = false) => document.dispatchEvent(new KeyboardEvent(type, { code, repeat, bubbles: true }));
  const pointer = (target, type, id, x = 50, y = 100) => target.dispatchEvent(new PointerEvent(type, {
    pointerId: id, pointerType: 'touch', clientX: x, clientY: y, bubbles: true, cancelable: true
  }));
  try {
    const defaults = Core.sanitizeSettings(null);
    assert(defaults.quality === 'high' && defaults.volume === .6, 'null saved settings use safe defaults');
    const invalid = Core.sanitizeSettings({ quality: 'unknown', sensitivity: NaN, volume: Infinity, reduced: 'false' });
    assert(invalid.quality === 'high' && invalid.sensitivity === 1 && invalid.volume === .6 && !invalid.reduced, 'invalid numbers/types cannot corrupt settings');
    const bounded = Core.sanitizeSettings({ sensitivity: 99, volume: -3, reduced: true, quality: 'xhigh' });
    assert(bounded.sensitivity === 2 && bounded.volume === 0 && bounded.reduced && bounded.quality === 'xhigh', 'settings clamp to supported ranges');
    const grid = ['1111111','1000001','1011101','1000101','1110101','1000001','1111111'].map(row => [...row].map(Number));
    const nav = new Core.Navigation(grid, 2), from = { x: 2, z: 2 }, goal = { x: 10, z: 10 };
    const path = nav.findPath(from, goal);
    assert(path.length > 0 && path.every(point => nav.canStand(point.x, point.z)), 'BFS finds walkable route around walls');
    assert(nav.findPath(from, { x: -2, z: -2 }).length === 0, 'out-of-map path target rejected');
    assert(!nav.clearSight({ x: 2, z: 4 }, { x: 10, z: 4 }), 'line of sight cannot pass through walls');
    assert(!nav.clearSight(from, { x: NaN, z: 2 }), 'non-finite ray rejected');
    const mover = { x: 2, z: 4 };
    nav.move(mover, 8, 0);
    assert(mover.x < 3 && nav.canStand(mover.x, mover.z), 'large movement cannot tunnel through a wall');
    const walker = { ...from }, remaining = [...path];
    for (let i = 0; i < 2000 && remaining.length; i++) {
      const target = remaining[0], dx = target.x - walker.x, dz = target.z - walker.z, length = Math.hypot(dx, dz);
      if (length < .06) { remaining.shift(); continue; }
      nav.move(walker, dx / length * Math.min(.09, length), dz / length * Math.min(.09, length), .25);
    }
    assert(Math.hypot(walker.x - goal.x, walker.z - goal.z) < .08, 'route can actually be traversed through corners');
    const house = Core.createHouse(), houseNav = new Core.HouseNavigation(house);
    const originalArea = 229;
    const expandedArea = house.floors.reduce((sum, layer) => sum + layer.flat().filter(cell => cell === 0).length, 0);
    assert(house.floors.length === 2 && expandedArea / originalArea > 2.85 && expandedArea / originalArea < 3.15, 'two-floor house provides approximately three times the original walkable area');
    const entrance = { x:18, z:32, y:1.62, floor:0, eyeHeight:1.62 };
    assert(houseNav.cellId({x:18,y:0,z:6,floor(){return this;}})>=0, 'Three.Vector3 floor method is not mistaken for floor metadata');
    const unreachable = [];
    house.floors.forEach((grid,floor)=>grid.forEach((row,z)=>row.forEach((cell,x)=>{
      const target={x:x*house.cell,z:z*house.cell,floor};
      if(cell===0 && houseNav.cellId(target)!==houseNav.cellId(entrance) && !houseNav.findPath(entrance,target).length)unreachable.push(target);
    })));
    assert(unreachable.length===0, 'every walkable cell on both floors is connected, including the room beside the stairs');
    function walkRoute(start, target) {
      const walker = { ...start }, route = houseNav.findPath(walker, target);
      let frames = 0, changedFloor = false;
      while(route.length && frames++ < 20000) {
        const next = route[0], dx = next.x-walker.x, dz = next.z-walker.z, distance = Math.hypot(dx,dz);
        if(distance < .04) { route.shift(); continue; }
        const before = walker.floor;
        houseNav.move(walker,dx/distance*Math.min(.07,distance),dz/distance*Math.min(.07,distance),.25);
        changedFloor ||= before !== walker.floor;
      }
      assert(route.length === 0 && walker.floor === target.floor && Math.hypot(walker.x-target.x,walker.z-target.z)<.05, 'player/enemy can traverse full route to floor ' + (target.floor+1));
      assert(Math.abs(walker.y-(target.floor*house.floorHeight+(walker.eyeHeight||0)))<.001, 'arrival height matches the destination floor');
      return { walker, changedFloor };
    }
    for(const target of house.talismans) walkRoute(entrance,target);
    const upstairs = walkRoute({x:18,z:6,floor:0},house.talismans[2]);
    assert(upstairs.changedFloor, 'enemy reaches upstairs through the staircase');
    const downstairs = walkRoute(upstairs.walker,{x:18,z:32,floor:0});
    assert(downstairs.changedFloor, 'enemy can descend and return to the entrance');
    walkRoute({...house.talismans[2],eyeHeight:1.62},entrance);
    assert(!houseNav.clearSight({x:66,z:6,floor:0},{x:66,z:6,floor:1}), 'ceilings block cross-floor sight and interaction');
    assert(houseNav.cellId({x:66,z:6,floor:0}) !== houseNav.cellId({x:66,z:6,floor:1}), 'AI goals distinguish vertically stacked cells');
    assert(houseNav.clearSight({x:42,z:32,floor:0},{x:44,z:32,floor:0}), 'enemy can see and catch the player on the stair flight');
    const underLanding = {x:52,z:32,floor:0};
    houseNav.move(underLanding,-8,0);
    assert(underLanding.floor===0 && underLanding.x>51, 'ground-floor corridor cannot teleport through the stair landing');
    const stairSide = {x:44,z:32,floor:0};
    houseNav.move(stairSide,0,-6);
    assert(stairSide.z>31 && stairSide.floor===0, 'stair sides cannot be exited through walls');
    const upperVoid = {x:38,z:32,floor:1};
    houseNav.move(upperVoid,5,0);
    assert(upperVoid.x<39 && upperVoid.floor===1, 'upper floor cannot step into the lower end of the stair void');
    assert(houseNav.findPath(entrance,{x:-2,z:-2,floor:1}).length===0, 'multi-floor navigation rejects out-of-map destinations');
    const beforeInvalid = {...entrance};
    assert(!houseNav.move(beforeInvalid,NaN,0) && beforeInvalid.x===entrance.x, 'multi-floor movement rejects non-finite input');
    assert(house.talismans.some(item=>item.floor===1), 'at least one talisman requires exploring upstairs');
    const energy = { value: 100, exhausted: false, sprint: false };
    for (let i = 0; i < 600 && !energy.exhausted; i++) Core.stepStamina(energy, energy.value, energy.exhausted, true, true, 1 / 60);
    assert(energy.exhausted && energy.value <= 1, 'sprint exhaustion latches');
    Core.stepStamina(energy, energy.value, energy.exhausted, true, true, 1 / 60);
    assert(!energy.sprint, 'holding sprint cannot jitter between walking and sprint at zero');
    let prematurelySprinted = false;
    while (energy.value < 25) { Core.stepStamina(energy, energy.value, energy.exhausted, true, true, 1 / 60); prematurelySprinted ||= energy.sprint; }
    assert(!prematurelySprinted, 'sprint stays disabled until recovery threshold');
    Core.stepStamina(energy, energy.value, energy.exhausted, true, true, 1 / 60);
    assert(energy.sprint && !energy.exhausted, 'sprint becomes available after recovery');
    await until(() => $('loading').classList.contains('hidden'), 'initial render');
    assert(snapshot().savedRigidDraws > 0, 'rigid voxel parts are instanced without removing animated joints');
    const environment = snapshot().environment;
    assert(new Set(environment.rooms).size === 18, 'eighteen rooms furnish the original house, east wing and upstairs');
    assert(snapshot().map.floors===2 && snapshot().map.talismans[2].floor===1, 'production scene uses the expanded two-floor layout');
    assert(environment.candles === 12 && environment.lanterns === 3 && environment.webs === 5, 'procedural candles, lanterns and cobwebs are present');
    assert(environment.rainVisible, 'window rain is present at high quality');
    const visual = snapshot().visual;
    assert(visual.mapDetail.textureSize===512 && visual.mapDetail.filtered, '512px map surfaces use linear filtering');
    assert(visual.mapDetail.shoji===24 && visual.mapDetail.joinery>300 && visual.mapDetail.props>3000, 'both floors include batched shoji and fine architectural details');
    assert(visual.mapDetail.detailRelief, 'fine map materials have high-quality surface relief');
    assert(visual.atmosphere && visual.surfaceRelief && visual.cloth, 'high quality includes atmosphere, relief and woven clothing');
    assert(visual.moonbeams === 12 && visual.mistLayers === 12 && visual.moonPools === 48, 'moonlight and mist extend through both floors and the east wing');
    const canvas = document.querySelector('#world canvas');
    canvas.requestPointerLock = () => Promise.resolve();
    $('sound-button').click(); $('sound-button').click();
    $('howto-button').click();
    assert(snapshot().modalDepth === 1, 'opening modal records a frozen scene');
    document.querySelector('[data-close="howto-modal"]').click();
    $('start-button').click();
    assert(snapshot().state === 'playing' && snapshot().collected === 0 && $('elapsed-time').textContent === '00:00', 'new game resets state, counter and timer');
    const before = snapshot();
    key('keydown', 'KeyW');
    await until(() => snapshot().elapsed - before.elapsed > .6, 'walking');
    key('keyup', 'KeyW');
    const after = snapshot();
    assert(Math.abs((before.player.z - after.player.z) / (after.elapsed - before.elapsed) - 2.55) < .05, 'walking speed matches simulated elapsed time');
    assert(after.navigationSearches - before.navigationSearches < 3, 'direct pursuit does not recompute BFS every frame');
    assert(after.environment.pathLength === 0, 'direct pursuit keeps no stale navigation waypoints');
    const joystick = $('joystick-zone');
    pointer(joystick, 'pointerdown', 101, 70, 650);
    pointer(joystick, 'pointermove', 101, 96, 618);
    pointer(joystick, 'pointerdown', 102, 250, 650);
    assert(snapshot().input.stickPointer === 101, 'second finger cannot steal movement joystick');
    pointer(document, 'pointercancel', 101);
    assert(snapshot().input.stickPointer === null && snapshot().input.stickX === 0, 'cancel releases movement and stick position');
    pointer(canvas, 'pointerdown', 201, innerWidth * .8, 300);
    pointer(canvas, 'pointerdown', 202, innerWidth * .7, 400);
    assert(snapshot().input.lookPointer === 201, 'second look finger cannot replace first look pointer');
    const yawBefore = snapshot().yaw;
    pointer(document, 'pointermove', 201, innerWidth * .8 + 20, 310);
    assert(snapshot().yaw !== yawBefore, 'touch look updates camera orientation');
    pointer(canvas, 'lostpointercapture', 201);
    assert(snapshot().input.lookPointer === null, 'lost look capture clears pointer');
    pointer($('run-button'), 'pointerdown', 301);
    pointer($('run-button'), 'pointerdown', 302);
    pointer(document, 'pointerup', 302);
    assert(snapshot().input.running && snapshot().input.runPointer === 301, 'unrelated finger release cannot cancel held sprint');
    pointer(document, 'pointercancel', 301);
    assert(!snapshot().input.running && snapshot().input.runPointer === null, 'sprint cancel clears ownership');
    $('pause-button').click();
    await wait(500);
    const paused = snapshot();
    await wait(700);
    assert(snapshot().elapsed === paused.elapsed, 'paused simulation time is frozen');
    assert(snapshot().renderFrames === paused.renderFrames, 'paused scene submits no extra rendering frames');
    assert(snapshot().visual.mistTime === paused.visual.mistTime, 'ground mist freezes with paused gameplay');
    assert(snapshot().environment.pendulumAngle === paused.environment.pendulumAngle && snapshot().environment.lanternAngle === paused.environment.lanternAngle, 'ambient prop animation freezes with gameplay');
    key('keydown', 'Escape', true);
    assert(snapshot().state === 'paused', 'repeating Escape cannot accidentally resume');
    $('pause-settings-button').click();
    assert(snapshot().modalDepth === 2, 'settings above pause tracks nested dialogs');
    const quality = $('quality-select'); quality.value = 'low'; quality.dispatchEvent(new Event('change'));
    await wait(500);
    assert(snapshot().quality === 'low', 'quality can change while paused');
    assert(!snapshot().environment.rainVisible, 'low quality disables window rain');
    assert(!snapshot().visual.atmosphere && !snapshot().visual.surfaceRelief, 'lightweight mode disables extra atmosphere and surface relief');
    assert(!snapshot().visual.mapDetail.detailRelief, 'low mode disables new detail surface relief');
    const reduced = $('reduce-effects'); reduced.checked = true; reduced.dispatchEvent(new Event('change'));
    await until(() => snapshot().environment.pendulumAngle === 0 && snapshot().environment.lanternAngle === 0, 'reduced motion applies while paused');
    assert(snapshot().environment.cameraRoll === 0 && snapshot().environment.handOffset === 0, 'reduced motion clears camera and hand sway immediately');
    assert(snapshot().environment.pendulumAngle === 0 && snapshot().environment.lanternAngle === 0, 'reduced motion stops decorative swinging');
    assert(snapshot().visual.mistTime === 0, 'reduced motion resets mist even inside paused settings');
    quality.value = 'high'; quality.dispatchEvent(new Event('change'));
    assert(snapshot().visual.atmosphere && snapshot().visual.surfaceRelief, 'returning to high restores atmospheric and surface detail');
    assert(snapshot().visual.mapDetail.detailRelief && snapshot().visual.mapDetail.props===visual.mapDetail.props, 'high mode restores relief without recreating fine geometry');
    assert(snapshot().visual.moonPools === visual.moonPools, 'quality changes reuse the existing moonlight instances');
    quality.value = 'low'; quality.dispatchEvent(new Event('change'));
    document.querySelector('[data-close="settings-modal"]').click();
    assert(snapshot().modalDepth === 1, 'closing settings retains underlying pause');
    $('resume-button').click();
    assert(snapshot().state === 'playing' && snapshot().modalDepth === 0, 'resume clears pause without stale modal state');
    key('keydown', 'KeyW');
    const resumedAt = snapshot().elapsed;
    await until(() => snapshot().elapsed > resumedAt + .25, 'reduced-motion walking');
    assert(snapshot().environment.handOffset === 0 && snapshot().environment.cameraRoll === 0, 'walking respects reduced camera and hand motion');
    window.dispatchEvent(new Event('blur'));
    assert(snapshot().state === 'paused' && snapshot().input.keyCount === 0, 'focus loss pauses and clears held keyboard keys');
    $('home-button').click(); $('start-button').click();
    assert(snapshot().collected === 0 && snapshot().elapsed === 0 && snapshot().stamina === 100 && !snapshot().exhausted, 'retry resets all gameplay and stamina state');
    assert(snapshot().player.floor===0 && snapshot().player.y===1.62 && snapshot().enemy.floor===0, 'retry restores both characters to the ground floor');
    assert($('game-hud').querySelector('.objective .hud-eyebrow').textContent==='1F / 本館', 'HUD identifies the current floor and wing');
    key('keydown', 'KeyS'); key('keydown', 'ShiftLeft');
    await until(() => snapshot().player.z > 33.6, 'approach exit');
    key('keyup', 'KeyS'); key('keyup', 'ShiftLeft');
    $('interact-button').click();
    assert($('game-message').textContent.includes('封じられている'), 'exit remains locked without talismans');
    const copy = snapshot(); copy.player.x = 999; copy.settings.volume = 999; copy.environment.rooms[0] = 'changed';
    assert(snapshot().player.x !== 999 && snapshot().settings.volume !== 999 && snapshot().environment.rooms[0] !== 'changed', 'diagnostics expose copies, never mutable game references');
    $('pause-button').click(); $('home-button').click(); $('start-button').click();
    console.info('[AUDIT METRICS] ' + JSON.stringify(snapshot()));
    document.body.dataset.auditTest = 'passed';
    console.info(`[AUDIT COMPLETE] ${checks} assertions passed.`);
  } catch (error) {
    document.body.dataset.auditTest = 'failed';
    console.error('[AUDIT FAILED] ' + error.message);
  }
})();
